-- ============================================================
--  SOCCER PRO EXPERIENCE - SCHEMA MULTI-TORNEO
--  Copia tutto e incolla nel SQL Editor di Supabase
-- ============================================================

-- Pulisce tutto
DROP TABLE IF EXISTS conferme_pending CASCADE;
DROP TABLE IF EXISTS knockout CASCADE;
DROP TABLE IF EXISTS marcatori CASCADE;
DROP TABLE IF EXISTS partite CASCADE;
DROP TABLE IF EXISTS girone_squadre CASCADE;
DROP TABLE IF EXISTS gironi CASCADE;
DROP TABLE IF EXISTS squadre CASCADE;
DROP TABLE IF EXISTS categorie CASCADE;
DROP TABLE IF EXISTS tornei CASCADE;

-- TORNEI
CREATE TABLE tornei (
  id bigint generated by default as identity primary key,
  nome text not null,
  data text default '',
  attivo boolean default true,
  created_at timestamptz default now()
);

-- CATEGORIE (collegate al torneo)
CREATE TABLE categorie (
  id bigint generated by default as identity primary key,
  torneo_id bigint references tornei(id) on delete cascade,
  nome text not null,
  qualificate integer default 2,
  formato text default 'semi',
  ordine integer default 0
);

-- SQUADRE (collegate al torneo)
CREATE TABLE squadre (
  id bigint generated by default as identity primary key,
  torneo_id bigint references tornei(id) on delete cascade,
  nome text not null,
  logo text
);

-- GIRONI
CREATE TABLE gironi (
  id bigint generated by default as identity primary key,
  categoria_id bigint references categorie(id) on delete cascade,
  nome text not null
);

-- GIRONE_SQUADRE
CREATE TABLE girone_squadre (
  id bigint generated by default as identity primary key,
  girone_id bigint references gironi(id) on delete cascade,
  squadra_id bigint references squadre(id) on delete cascade,
  posizione integer default 0,
  unique(girone_id, squadra_id)
);

-- PARTITE
CREATE TABLE partite (
  id bigint generated by default as identity primary key,
  girone_id bigint references gironi(id) on delete cascade,
  home_id bigint references squadre(id),
  away_id bigint references squadre(id),
  gol_home integer default 0,
  gol_away integer default 0,
  giocata boolean default false,
  created_at timestamptz default now()
);

-- MARCATORI
CREATE TABLE marcatori (
  id bigint generated by default as identity primary key,
  partita_id bigint references partite(id) on delete cascade,
  squadra_id bigint references squadre(id),
  nome text not null,
  minuto text
);

-- KNOCKOUT
CREATE TABLE knockout (
  id bigint generated by default as identity primary key,
  categoria_id bigint references categorie(id) on delete cascade,
  round_name text not null,
  round_order integer default 0,
  match_order integer default 0,
  home_id bigint references squadre(id),
  away_id bigint references squadre(id),
  gol_home integer default 0,
  gol_away integer default 0,
  giocata boolean default false,
  is_consolazione boolean default false
);

-- CONFERME PENDING (bot Telegram)
CREATE TABLE conferme_pending (
  chat_id bigint primary key,
  partita_id bigint,
  gol_home integer,
  gol_away integer,
  tipo text default 'sovrascrittura',
  opzioni text default '[]',
  sq2_id bigint,
  nome1 text,
  nome2 text,
  g1 integer,
  g2 integer,
  created_at timestamptz default now()
);

-- ============================================================
--  RLS
-- ============================================================
ALTER TABLE tornei ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorie ENABLE ROW LEVEL SECURITY;
ALTER TABLE squadre ENABLE ROW LEVEL SECURITY;
ALTER TABLE gironi ENABLE ROW LEVEL SECURITY;
ALTER TABLE girone_squadre ENABLE ROW LEVEL SECURITY;
ALTER TABLE partite ENABLE ROW LEVEL SECURITY;
ALTER TABLE marcatori ENABLE ROW LEVEL SECURITY;
ALTER TABLE knockout ENABLE ROW LEVEL SECURITY;
ALTER TABLE conferme_pending ENABLE ROW LEVEL SECURITY;

-- ============================================================
--  POLICY
-- ============================================================
CREATE POLICY "pub" ON tornei FOR SELECT USING (true);
CREATE POLICY "all" ON tornei FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "pub" ON categorie FOR SELECT USING (true);
CREATE POLICY "all" ON categorie FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "pub" ON squadre FOR SELECT USING (true);
CREATE POLICY "all" ON squadre FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "pub" ON gironi FOR SELECT USING (true);
CREATE POLICY "all" ON gironi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "pub" ON girone_squadre FOR SELECT USING (true);
CREATE POLICY "all" ON girone_squadre FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "pub" ON partite FOR SELECT USING (true);
CREATE POLICY "all" ON partite FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "pub" ON marcatori FOR SELECT USING (true);
CREATE POLICY "all" ON marcatori FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "pub" ON knockout FOR SELECT USING (true);
CREATE POLICY "all" ON knockout FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "all" ON conferme_pending FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
--  REALTIME
-- ============================================================
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND tablename='partite') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE partite;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND tablename='marcatori') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE marcatori;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND tablename='knockout') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE knockout;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND tablename='tornei') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE tornei;
  END IF;
END $$;
